version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8058:8058"
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: docker
    volumes:
      - C:/Users/Cris-SX/.aws:/home/appuser/.aws:ro
    networks:
      - app_network

  db:
    image: postgres:15
    container_name: vital-sanity-docker-compose
    restart: always
    ports:
      - "5058:5432"
    environment:
      POSTGRES_USER: vital
      POSTGRES_PASSWORD: vital
      POSTGRES_DB: vital
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./src/main/resources/sql/database-script/seed_develop_db.sql:/docker-entrypoint-initdb.d/seed_develop_db.sql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
